---

- name: create templates based on group_vars/all
  template:
    src: "{{item}}.j2"
    dest: "{{item}}"
    mode: 0775
  loop:
    - "{{playbook_dir}}/govc/source-govc-vars.sh"
    - "{{playbook_dir}}/govc/start-vcenter-from-esxi.sh"


