---
kind: Namespace
apiVersion: v1
metadata:
  name: istio-system
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system

spec:
  profile: default
  revision: "1_7_5"

  # avoid rate limit on docker hub for istio envoy proxy
  # I get pull errors using gcr.io from microk8s (might need gcr secret)
  # so just allow default docker.io/istio
  #values:
  #  global:
  #    hub: grc.io/istio-release

  #values:
    # https://console.cloud.google.com/gcr/images/istio-release/GLOBAL
    #pilot:
    #  hub: gcr.io/istio-release/pilot
    # gcr.io only has single version, not the one we need
    #prometheus:
    #  hub: gcr.io/istio-release/prom/promethus
    # only on quay
    #kiali:
    #  hub:
  addonComponents:
    kiali:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
    pilot:
      enabled: true

  components:
    ingressGateways:
      - namespace: istio-system
        name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
            maxReplicas: 1
            
          service:
            ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              nodePort: 32600
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              nodePort: 32601
              port: 443
              protocol: TCP
              targetPort: 8443
            - name: tcp
              port: 31400
              protocol: TCP
              targetPort: 31400
            - name: tls
              port: 15443
              protocol: TCP
              targetPort: 15443

          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.loadBalancerIP
                  value: 192.168.125.25
                # needs to match MetalLB endpoint
                - path: spec.loadBalancerSourceRanges
                  value: [ 10.0.0.0/8, 192.0.0.0/8 ]

