---
kind: Namespace
apiVersion: v1
metadata:
  name: istio-system
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system

spec:
  profile: default
  revision: "1-7-8"

  addonComponents:
    kiali:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
    pilot:
      enabled: true

  components:
    ingressGateways:
      - namespace: istio-system
        name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
            maxReplicas: 1
            
          service:
            ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              nodePort: 32600
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              nodePort: 32601
              port: 443
              protocol: TCP
              targetPort: 8443
            - name: tcp
              port: 31400
              protocol: TCP
              targetPort: 31400
            - name: tls
              port: 15443
              protocol: TCP
              targetPort: 15443

          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.loadBalancerIP
                  value: 192.168.142.253
                # not using MetalLB, so do not need this
                # needs to match MetalLB endpoint
                #- path: spec.loadBalancerSourceRanges
                #  value: [ 10.0.0.0/8, 192.0.0.0/8 ]

