---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: default
  # CHANGED: should have installed with revision so canary upgrades possible
  # but settting it now and doing kubectl apply will still create data plane with revisions:
  #   service/istiod-1-6-6
  #   Mutatingwebhookconfigurations/istio-sidecar-injector-1-6-6
  #
  # service/istio-ingressgateway will not change
  # should install with revision so canary upgrades possible
  revision: 1-6-6

  addonComponents:
    kiali:
      enabled: true
    grafana:
      enabled: true
    ### CHANGED: need to enable pilot addon before moving to 1.7.5
    # else the ingress gateway does not upgrade which blocks the upgrade process
    pilot:
      enabled: true

  components:
    ingressGateways:
      - namespace: istio-system
        name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
            maxReplicas: 1
          service:
            ports:
              - name: status-port
                port: 15021
                protocol: TCP
                targetPort: 15021
              - name: http2
                port: 80
                protocol: TCP
                targetPort: 8080
              - name: https
                # must be in range 30000-32767, static so LB do not have to be reconfigured
                nodePort: 32056
                port: 443
                protocol: TCP
                targetPort: 8443
              - name: tls
                port: 15443
                protocol: TCP
                targetPort: 15443
              - port: 31400
                name: tcp
          # no service annotations needed
          #serviceAnnotations:
          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.loadBalancerIP
                  value: 192.168.142.253
