---

# save IP address of ansible orchestrator
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - set_fact:
        hostvm_ip: "{{ hostvm_ip | default(ansible_default_ipv4.address) }}"
    - debug: msg="{{hostvm_ip}}"

# IP address of ansible orchestrator still available
- hosts: adminws
  tasks:
    - debug: msg="from local {{hostvars['localhost']['hostvm_ip']}}"
  roles:
    - generate-adminws-files

