---

- hosts: anthos_seedvm
  gather_facts: yes
  become: yes
  vars:
    # add all in this group to 'docker' group
    docker_member_group: "ubuntu"

  roles:
    - fix-google-apt-key
    - anthos-seedvm-prereq
    - kubectl-gcloud-apt
    - k9s
    - govc-cli
    - docker

