# copy this to the admin workstation after completion
hostconfig:
  dns: "192.168.2.239"
  tod: "time.google.com"
  otherdns:
  - "8.8.8.8"
  - "8.8.4.4"
  othertod:
  - "ntp.ubuntu.com"
  searchdomainsfordns:
  - "home.lab"
blocks:
  - netmask: "255.255.255.0"
    gateway: "192.168.141.1"
    ips:
    - ip: "192.168.141.251"
      hostname: "seesaw-vm"
