# copy this to the admin workstation after completion
hostconfig:
  dns: 192.168.2.239
  tod: time.google.com
  otherdns:
  - 8.8.8.8
  - 8.8.4.4
  othertod:
  - ntp.ubuntu.com
  searchdomainsfordns:
  - "home.lab"
blocks:
  - netmask: 255.255.255.0
    gateway: 192.168.142.1
    ips:
    - ip: 192.168.142.230
      hostname: user-host1
    - ip: 192.168.142.231
      hostname: user-host2
    - ip: 192.168.142.232
      hostname: user-host3
    - ip: 192.168.142.233
      hostname: user-host4
    - ip: 192.168.142.234
      hostname: user-host5
