apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: defaultns-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods","secrets","services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  # intentionally missing 'deployments'
  resources: ["daemonsets","replicasets","statefulsets"]
  verbs: ["get", "watch", "list"]
