# specifies which subjects are bound to cluster-wide 'pod-reader' role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods
subjects:
- kind: Group
  name: engineers
  apiGroup: rbac.authorization.k8s.io
#- kind: User
#  name: xxxxxx
#  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
