apiVersion: v1
kind: Secret
metadata:
  name: cloud-console-reader-secret
  annotations:
    kubernetes.io/service-account.name: "remote-cloud-console-reader"
type: kubernetes.io/service-account-token
data:
  # mysecret!
  mysecret: bXlzZWNyZXQhCg==
