---

- name: create AdminWS files, tailored to anthos version 1.4
  template:
    src: "{{item}}.{{anthos_template_version}}.j2"
    dest: "/home/ubuntu/{{ item|basename }}"
    mode: 0775
  loop:
    # for creating admin cluster
    - "{{playbook_dir}}/needed_on_adminws/14/admin-cluster.yaml"
    - "{{playbook_dir}}/needed_on_adminws/14/admin-hostconfig.yaml"
    - "{{playbook_dir}}/needed_on_adminws/14/admin-seesaw-hostconfig.yaml"
    # for creating user cluster
    - "{{playbook_dir}}/needed_on_adminws/14/user-cluster.yaml"
    - "{{playbook_dir}}/needed_on_adminws/14/user-seesaw-hostconfig.yaml"
    - "{{playbook_dir}}/needed_on_adminws/14/user-hostconfig.yaml"
  when: anthos_template_version==14

- name: create AdminWS, tailored to anthos version {{anthos_template_version}}
  template:
    src: "{{item}}.{{anthos_template_version}}.j2"
    dest: "/home/ubuntu/{{ item|basename }}"
    mode: 0775
  loop:
    # for creating admin cluster
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/admin-cluster.yaml"
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/admin-block.yaml"
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/admin-seesaw-block.yaml"
    # for creating user cluster
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/user-cluster.yaml"
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/user-seesaw-block.yaml"
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/user-block.yaml"
  when: anthos_template_version>14

- name: create AdminWS files for CoreDNS, tailored to anthos version {{anthos_template_version}}
  template:
    src: "{{item}}.{{anthos_template_version}}.j2"
    dest: "/home/ubuntu/{{ item|basename }}"
    mode: 0775
  loop:
    # for configuring CoreDNS
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/configure-clusterdns.yaml"
  when: anthos_template_version>=19

