---

- name: create AdminWS files, tailored to anthos version 1.4
  template:
    src: "{{item}}.{{anthos_template_version}}.j2"
    dest: "/home/ubuntu/{{ item|basename }}"
    mode: 0775
  loop:
    # for creating admin cluster
    - "{{playbook_dir}}/needed_on_adminws/14/admin-cluster.yaml"
    - "{{playbook_dir}}/needed_on_adminws/14/admin-hostconfig.yaml"
    - "{{playbook_dir}}/needed_on_adminws/14/admin-seesaw-hostconfig.yaml"
    # for creating user cluster
    - "{{playbook_dir}}/needed_on_adminws/14/user-cluster.yaml"
    - "{{playbook_dir}}/needed_on_adminws/14/user-seesaw-hostconfig.yaml"
    - "{{playbook_dir}}/needed_on_adminws/14/user-hostconfig.yaml"
  when: anthos_template_version == 14

- name: create AdminWS, tailored to anthos version {{anthos_template_version}} (>14 and < 113)
  template:
    src: "{{item}}.{{anthos_template_version}}.j2"
    dest: "/home/ubuntu/{{ item|basename }}"
    mode: 0775
  loop:
    # for creating admin cluster
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/admin-cluster.yaml"
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/admin-block.yaml"
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/admin-seesaw-block.yaml"
    # for creating user cluster
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/user-cluster.yaml"
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/user-seesaw-block.yaml"
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/user-block.yaml"
  when: anthos_template_version>14 and anthos_template_version < 113

- name: create AdminWS, tailored to anthos version {{anthos_template_version}} (>= 113)
  template:
    src: "{{item}}.{{anthos_template_version}}.j2"
    dest: "/home/ubuntu/{{ item|basename }}"
    mode: 0775
  loop:
    # for creating admin cluster
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/admin-cluster.yaml"
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/admin-block.yaml"
    # for creating user cluster
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/user-cluster.yaml"
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/user-block.yaml"
  when: anthos_template_version >= 113

- name: create AdminWS files for CoreDNS, tailored to anthos version {{anthos_template_version}} (>= 19)
  template:
    src: "{{item}}.{{anthos_template_version}}.j2"
    dest: "/home/ubuntu/{{ item|basename }}"
    mode: 0775
  loop:
    # for configuring CoreDNS, newly introduced in Anthos 1.9
    - "{{playbook_dir}}/needed_on_adminws/{{anthos_template_version}}/configure-clusterdns.yaml"
  when: anthos_template_version >= 19

- name: copy over json service account files for AdminWS
  copy:
    src: "{{item}}"
    dest: "/home/ubuntu"
    mode: 0664
  with_fileglob: "{{playbook_dir}}/needed_on_adminws/*.json"

- name: copy over script for AdminWS
  copy:
    src: "{{playbook_dir}}/needed_on_adminws/adminws_ssh_increase_timeout.sh"
    dest: "/home/ubuntu"
    mode: 0755

- name: copy over entire k8s directory for AdminWS
  copy:
    src: "{{playbook_dir}}/needed_on_adminws/k8s"
    dest: "/home/ubuntu"
    mode: 0775

