---
# https://cloud.google.com/sdk/docs/install#deb

- name: prereq packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: is google key already loaded into keyring
  command: apt-key list --list-signatures
  register: google_key

- name: get google key
  shell: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  when: not '6A030B21BA07F4FB' in google_key.stdout and not apt_proxy is defined

- name: add google repository
  apt_repository:
    repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    filename: google-cloud-sdk
    update_cache: yes
    mode: 0644
    #validate_certs: no

- name: install google cloud sdk with apt (and not component manager enabled)
  package:
    name:
      - google-cloud-sdk
    state: present
    update_cache: yes

- name: install kubectl and anthos-auth using apt, because we used apt to install google-cloud-sdk and component manager not enabled when you do that
  package:
    name:
      - kubectl
      - google-cloud-sdk-anthos-auth
    state: present
    update_cache: yes
