---

- name: disable Ubuntu auto-update
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
    content: |
      APT::Periodic::Update-Package-Lists "0";
      APT::Periodic::Unattended-Upgrade "0";

- name: install list of packages, debian based
  apt:
    pkg:
    - net-tools # netstat
    - jq # json tool
    - vim
    - curl
    - whois
    - zip
    - unzip
    - ntpdate
    - netcat
    - ldap-utils # for ldapsearch
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: update editor preferences, Ubuntu
  command: /usr/bin/update-alternatives --set editor /usr/bin/vim.basic
  register: command_result
  changed_when: "command_result.stdout != ''"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#- debug: msg="{{command_result}}"

#- name: update python preferences, Ubuntu
#  command: update-alternatives --install /usr/bin/python python /usr/bin/python3 20
#  register: command_result
#  changed_when: "command_result.stdout != ''"
#  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#- debug: msg="{{command_result}}"

- name: vimrc skeleton
  copy:
    dest: /etc/skel/.vimrc
    content: |
      colorscheme desert
      syntax on
      set paste
      set ruler
      autocmd FileType python setlocal ts=4 sts=4 sw=4 expandtab number autoindent
      autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab autoindent
      set foldenable
      set foldlevelstart=20
      set foldmethod=indent
      nnoremap <space> za

- name: default .bash_profile
  copy:
    dest: "/home/ubuntu/.bash_profile"
    owner: ubuntu
    group: ubuntu
    mode: 0664
    content: |
      export KUBECONFIG=/home/ubuntu/user1-kubeconfig
      alias lsl='ls -latr'
      export EDITOR=vim
      export VISUAL=vim

- name: extend TMOUT so ssh client does timeout, 600 seconds
  shell:
    cmd: sed -i 's/TMOUT=.*/TMOUT=600/' $(grep -sr ^TMOUT -l)
    chdir: /etc/profile.d
